on:
  push:
    branches:
      - main
      - assignment1_wanhakimi
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - Malay
        uses: dephraiim/translate-readme@main
        with:
          LANG: ms
      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - Germany
        uses: dephraiim/translate-readme@main
        with:
          LANG: de
      - name: Adding README - Japanese
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja 